[package]
name = "secure-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"                     # <- 追加
x25519-dalek = "2.0.1"
chacha20poly1305 = { version = "0.11.0-rc.0", features = ["alloc"] }
