[package]
name = "secure-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
x25519-dalek = "2.0.1"   # stable
chacha20poly1305 = "0.10" # stable
rand = { version = "0.8", features = ["std"] }
rand_core = { version = "0.6", features = ["getrandom"] }
